### ISSUE TITLE
Doesn't work with version 5.5.3

### ISSUE THREAD

**Issue by FredrikWendt** [nielslange/smntcs-deactivate-image-compression#17]
This seems like a nice feature, unfortunately it has no effect after being installed and activated through admin UI. Uploaded images still gets compressed. I've not looked into why.

**Comment by FredrikWendt** [comment]
Actually, I failed to realize we had another webp plugin which converted the image anyway.

**Comment by nielslange** [comment]
> Actually, I failed to realize we had another webp plugin which converted the image anyway.

That means that the plugin works as expected, right?
